# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
