# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postry_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postry',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
