# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postry'),
    ]

    operations = [
        migrations.AddField(
            model_name='postry',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
